### PR TITLE
Allow manipulation of default session configuration

### PR DESCRIPTION
**Pull request by bdpedigo**

### CODE REVIEW

**Comment by bdpedigo** [comment]
went back and forth about how to expose all of these parameters (or not) and just leave them in a config (SESSION DEFAULTS). it felt like it was becoming too many parameters to add to every single client so I opted for the latter for most of them

**Comment by fcollman** [comment]
can you add in the new skeleton service?

**Comment by bdpedigo** [comment]
@fcollman yes merged those in

**Comment by bdpedigo** [comment]
@fcollman added a test and docs (including a bit in the tutorial). Good to go on my end

**Review by fcollman — APPROVED** [review]

**Pull request merged**
