### PR TITLE
Addition of four new inequality filters

### PR DESCRIPTION
**Pull request by kebwi**

### CODE REVIEW

**Comment by fcollman** [comment]
when the materialization version is bumped you should add the check that the server is running the required version of materialization when using these keyword arguments, else the user will get a 500 error that wont be that obvious what is wrong

**Comment by fcollman** [comment]
materialization engine >=4.34.0 has it

**Comment by kebwi** [comment]
Are you saying I should add that to the requirements.txt for CAVEclient?

**Comment by bdpedigo** [comment]
@kebwi https://github.com/CAVEconnectome/CAVEclient/blob/1d08a9b49a86fc0fa6ac52123ea709c535682b73/caveclient/chunkedgraph.py#L812 here's an example usage of a decorator I wrote for doing this kind of check on the version running on the server before executing the query

**Comment by kebwi** [comment]
@fcollman @bdpedigo I believe I've incorporated the server version check correctly. I tested it with "4.34.1" and it refused to run the query and then set it to "4.34.0" and committed it. So I think it works.

**Pull request merged**
